'use client'
import Layout from '@/components/Layout'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { motion } from 'framer-motion'
import { Component } from 'react'
import Container from '@/components/Container'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Layout>
      <Container>{children}</Container>
    </Layout>
  )
}
